name: Windows

on:
  pull_request:
    types: [main]
  push:
    branches: [main]

jobs:
  build:
    name: "Build ${{ matrix.platform }} in ${{ matrix.build_type }}"
    strategy:
      matrix:
        platform: [windows]
        build_type: [Release]
    env:
      working-directory: ./Homework
      PARALLEL: -j 2
    runs-on: "${{ matrix.platform }}-latest"
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      
      - name: Check
        run: ls

      - name: Configure
        run: cmake -H"." -B"build/${{ matrix.platform }}"

      - name: "Build ${{ matrix.platform }} in ${{ matrix.build_type }}"
        run: cmake --build "build/${{ matrix.platform }}" --target BUILD_ALL --config ${{ matrix.build_type }} ${{ env.PARALLEL }}